name: Call CDAC API to validate diagram

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  save-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files in current directory
        run: ls -al
      - name: Validate diagram
        run: curl --fail https://dummyjson.com/products/999SDSA
      - name: Update diagram
        run: curl --fail https://dummyjson.com/products/1